"""Network Checker data assets (JSON, converted from the vendored upstream app).

The data under data/ was generated by scripts/convert_checker_data.py from the
GPL-3.0 mirarr-app/network-checker project.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_DATA_DIR = Path(__file__).parent


@lru_cache(maxsize=None)
def _load(name: str) -> Any:
    with open(_DATA_DIR / f"{name}.json", encoding="utf-8") as fh:
        return json.load(fh)


def cloudflare_ips() -> list[str]:
    return list(_load("cloudflareIps"))


def akamai_ips() -> list[str]:
    return list(_load("akamaiIps"))


def akamai_ip_ranges() -> list[str]:
    return list(_load("akamai_ip_ranges"))


def edge_ip_ranges() -> list[str]:
    return list(_load("edge_ip_ranges"))


def dns_providers() -> list[dict]:
    return list(_load("dns_providers"))


def top_domains() -> list[str]:
    return list(_load("top_domains"))


def dns_ranges() -> list[dict]:
    return list(_load("dns_ranges"))


def netlify_predefined() -> dict:
    return _load("netlify_predefined")